# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: native
font_size: L

# SEO

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type: Organization

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type: ''

# Organization name (optional)
org_name: 'Van der Laan & Science'

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description: The Van der Laan Lab has been a center for the research of atherosclerotic genetics, teaching, and practice since its founding in 2016.

twitter: 'swvanderlaan'

# Contact (edit or remove options as required)

email: s.w.vanderlaan-2@umcutrecht.nl
phone: +31 (0)88 756 76 96
address:
  street: Heidelberglaan 100
  city: Utrecht
  region:
  postcode: '3584 CX'
  country: the Netherlands
  country_code: NL
coordinates:
  latitude: '52.086567'
  longitude: '5.1781403'
directions:
office_hours:
  - 'Everyday of the week; or email for appointment.'
appointment_url: 'https://calendly.com/swvanderlaan'
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
